@DashBoredAPI_HostAddress = http://localhost:8080

GET {{DashBoredAPI_HostAddress}}/todos/
Accept: application/json

###

GET {{DashBoredAPI_HostAddress}}/todos/1
Accept: application/json

###
