# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  dashboredapi:
    image: dashboredapi
    build:
      context: .
      dockerfile: DashBored.Api/Dockerfile
    ports:
      - 5130:5130
