GET  http://localhost:5187/
###
GET  http://localhost:5187/posts
###
GET  http://localhost:5187/posts/1
###
POST  http://localhost:5187/posts
Content-Type: application/json

{
    "Name":"Posted post aaa",
    "Description":"Posted post desc",
    "Date":"2012-10-10"
}

###
PUT  http://localhost:5187/posts/1
Content-Type: application/json

{
    "Name":"New post1 name",
    "Description":"New description",
    "Date": "2024-01-02"
}
###
DELETE  http://localhost:5187/posts/1